Updated the video upload endpoint to a placeholder URL and added error handling for invalid JSON responses from the server.
Prompt: Errors from dev tools: index-bcf02a8b.js:271 Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
(anonymous) @ index-bcf02a8b.js:271
Show 1 more frame
Show less
mtgm.js:92 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. This event type is deprecated, and will be removed from this browser very soon. Usage of this event listener will cause performance issues today, and represents a large risk of future site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information.
(anonymous) @ mtgm.js:92
Show 1 more frame
Show less
2index-D3qGech7.js:375 Error uploading video: SyntaxError: Unexpected token '<', "<html lang"... is not valid JSON
u @ index-D3qGech7.js:375
preview--gemini-vide….gptengineer.run/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
2index-D3qGech7.js:375 Error uploading video: SyntaxError: Unexpected token '<', "<html lang"... is not valid JSON
u @ index-D3qGech7.js:375
await in u (async)
Nw @ index-D3qGech7.js:37
Uw @ index-D3qGech7.js:37
Hw @ index-D3qGech7.js:37
Yp @ index-D3qGech7.js:37
ey @ index-D3qGech7.js:37
(anonymous) @ index-D3qGech7.js:37
Jf @ index-D3qGech7.js:40
Cv @ index-D3qGech7.js:37
Qu @ index-D3qGech7.js:37
Tf @ index-D3qGech7.js:37
sk @ index-D3qGech7.js:37